source 'https://rubygems.org'

gem 'rails', '4.1.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'ask', path: '../../../ask'

gem 'carrierwave'
gem 'coffee-rails'
gem 'haml'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'sass-rails'
gem 'sqlite3'
gem 'therubyracer', :platforms => :ruby
gem 'uglifier', '>= 1.0.3'


group :development, :test do
  gem 'pry'
  gem 'better_errors'
  gem 'binding_of_caller'

  gem 'rspec-rails'
  gem 'rspec'
  gem 'factory_girl_rails'
  gem 'faker'

  gem 'capybara'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'guard-rspec'
end

